### ISSUE TITLE
Spacing of blank squares on iPhone

### ISSUE THREAD

**Issue by gitonthescene** [dancek/bqnsweeper#1]
Hi there, this looks super fun.  FWIW, while it looks fine on the desktop the spaces don't render as nicely on my iPhone.  I created a pull request which I think helps.  It also includes a link to this project.  Please let me know what you think.

**Comment by gitonthescene** [comment]
Here's how it renders on my iPhone in Safari:

![IMG_4F8C37913CCE-1](https://user-images.githubusercontent.com/45531702/174292912-ae7e8fdd-c2a8-408f-af5d-7f2f5e1151c9.jpeg)

**Comment by dancek** [comment]
Hopefully fixed by #2.

**Comment by gitonthescene** [comment]
It definitely looks better now.  Thanks.
